### ISSUE TITLE
session video link?

### ISSUE THREAD

**Issue by sachinbhutani** [d3xter666/ui5con-2019-mean-stack-with-ui5#2]
Hi, 
not really an issue, just wanted to check if there's a link to the recorded session of this project for integration of SAPUI5 with MExN stack  ? 
 I could find multiple ui5con videos on youtube, but not for this session.

**Comment by d3xter666** [comment]
Hi,

Unfortunately, it was not recorded as it was a hands-on session.

Regards,
Yavor
